---
apiVersion: v1
kind: Service
metadata:
  name: jinja-frontend-svc
  namespace: jinja-dev
spec:
  selector:
    app: jinja-frontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32200
